---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfiles
  image: hadolint/hadolint
  commands:
  - hadolint */Dockerfile

trigger:
  event:
  - pull_request
  - push
  ref:
    exclude:
    - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test_1.10_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  image: plugins/docker
  settings:
    dockerfile: 1.10-php7.4/Dockerfile
    dry_run: true
    repo: mwalbeck/composer

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_1.10_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  image: plugins/docker
  settings:
    dockerfile: 1.10-php8.0/Dockerfile
    dry_run: true
    repo: mwalbeck/composer

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_2.0_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  image: plugins/docker
  settings:
    dockerfile: 2.0-php7.4/Dockerfile
    dry_run: true
    repo: mwalbeck/composer

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_2.0_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  image: plugins/docker
  settings:
    dockerfile: 2.0-php8.0/Dockerfile
    dry_run: true
    repo: mwalbeck/composer

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_1.10_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php7.4
    APP_NAME: COMPOSER
    DOCKERFILE_PATH: 1.10-php7.4/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  image: plugins/docker
  settings:
    dockerfile: 1.10-php7.4/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_1.10_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php8.0
    APP_NAME: COMPOSER
    DOCKERFILE_PATH: 1.10-php8.0/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  image: plugins/docker
  settings:
    dockerfile: 1.10-php8.0/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_2.0_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php7.4
    APP_NAME: COMPOSER
    DOCKERFILE_PATH: 2.0-php7.4/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  image: plugins/docker
  settings:
    dockerfile: 2.0-php7.4/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_2.0_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php8.0
    APP_NAME: COMPOSER
    CUSTOM_TAGS: latest
    DOCKERFILE_PATH: 2.0-php8.0/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  image: plugins/docker
  settings:
    dockerfile: 2.0-php8.0/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

...
