---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfiles
  pull: if-not-exists
  image: hadolint/hadolint:latest-debian
  commands:
  - hadolint --version
  - hadolint */Dockerfile

trigger:
  event:
  - pull_request
  - push
  ref:
    exclude:
    - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test_1_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 1-php7.4/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_1_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 1-php8.0/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_2_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 2-php7.4/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_2_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 2-php8.0/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_2_php8.1

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 2-php8.1/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_1_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php7.4
    APP_NAME: COMPOSER
    DOCKERFILE_PATH: 1-php7.4/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 1-php7.4/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  pull: if-not-exists
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_1_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php8.0
    APP_NAME: COMPOSER
    DOCKERFILE_PATH: 1-php8.0/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 1-php8.0/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  pull: if-not-exists
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_2_php7.4

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php7.4
    APP_NAME: COMPOSER
    DOCKERFILE_PATH: 2-php7.4/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 2-php7.4/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  pull: if-not-exists
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_2_php8.0

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php8.0
    APP_NAME: COMPOSER
    DOCKERFILE_PATH: 2-php8.0/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 2-php8.0/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  pull: if-not-exists
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_2_php8.1

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: php8.1
    APP_NAME: COMPOSER
    CUSTOM_TAGS: latest
    DOCKERFILE_PATH: 2-php8.1/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 2-php8.1/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username

- name: notify
  pull: if-not-exists
  image: plugins/matrix
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: signature
hmac: 778babaa33fd2166491abc4e7326593097433fadb6301563b6d4b3b21c1d6400

...
