---
kind: pipeline
name: lint
steps:
- commands:
  - hadolint --version
  - hadolint */Dockerfile
  image: hadolint/hadolint:latest-debian
  name: Lint Dockerfiles
  pull: if-not-exists
trigger:
  event:
  - pull_request
  - push
  ref:
    exclude:
    - refs/heads/renovate/*
type: docker
---
depends_on:
- lint
kind: pipeline
name: test_1.10_php7.4
steps:
- image: plugins/docker
  name: build test
  pull: if-not-exists
  settings:
    dockerfile: 1.10-php7.4/Dockerfile
    dry_run: "true"
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
trigger:
  event:
  - pull_request
type: docker
---
depends_on:
- lint
kind: pipeline
name: test_1.10_php8.0
steps:
- image: plugins/docker
  name: build test
  pull: if-not-exists
  settings:
    dockerfile: 1.10-php8.0/Dockerfile
    dry_run: "true"
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
trigger:
  event:
  - pull_request
type: docker
---
depends_on:
- lint
kind: pipeline
name: test_2.0_php7.4
steps:
- image: plugins/docker
  name: build test
  pull: if-not-exists
  settings:
    dockerfile: 2.0-php7.4/Dockerfile
    dry_run: "true"
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
trigger:
  event:
  - pull_request
type: docker
---
depends_on:
- lint
kind: pipeline
name: test_2.0_php8.0
steps:
- image: plugins/docker
  name: build test
  pull: if-not-exists
  settings:
    dockerfile: 2.0-php8.0/Dockerfile
    dry_run: "true"
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
trigger:
  event:
  - pull_request
type: docker
---
depends_on:
- lint
kind: pipeline
name: release_1.10_php7.4
steps:
- environment:
    APP_ENV: php7.4
    APP_NAME: COMPOSER
    CUSTOM_TAGS: ""
    DOCKERFILE_PATH: 1.10-php7.4/Dockerfile
    VERSION_TYPE: docker_env
  image: mwalbeck/determine-docker-tags
  name: determine tags
  pull: if-not-exists
- image: plugins/docker
  name: build and publish
  pull: if-not-exists
  settings:
    dockerfile: 1.10-php7.4/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
- image: plugins/matrix
  name: notify
  pull: if-not-exists
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success
trigger:
  branch:
  - master
  event:
  - push
type: docker
---
depends_on:
- lint
kind: pipeline
name: release_1.10_php8.0
steps:
- environment:
    APP_ENV: php8.0
    APP_NAME: COMPOSER
    CUSTOM_TAGS: ""
    DOCKERFILE_PATH: 1.10-php8.0/Dockerfile
    VERSION_TYPE: docker_env
  image: mwalbeck/determine-docker-tags
  name: determine tags
  pull: if-not-exists
- image: plugins/docker
  name: build and publish
  pull: if-not-exists
  settings:
    dockerfile: 1.10-php8.0/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
- image: plugins/matrix
  name: notify
  pull: if-not-exists
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success
trigger:
  branch:
  - master
  event:
  - push
type: docker
---
depends_on:
- lint
kind: pipeline
name: release_2.0_php7.4
steps:
- environment:
    APP_ENV: php7.4
    APP_NAME: COMPOSER
    CUSTOM_TAGS: ""
    DOCKERFILE_PATH: 2.0-php7.4/Dockerfile
    VERSION_TYPE: docker_env
  image: mwalbeck/determine-docker-tags
  name: determine tags
  pull: if-not-exists
- image: plugins/docker
  name: build and publish
  pull: if-not-exists
  settings:
    dockerfile: 2.0-php7.4/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
- image: plugins/matrix
  name: notify
  pull: if-not-exists
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success
trigger:
  branch:
  - master
  event:
  - push
type: docker
---
depends_on:
- lint
kind: pipeline
name: release_2.0_php8.0
steps:
- environment:
    APP_ENV: php8.0
    APP_NAME: COMPOSER
    CUSTOM_TAGS: latest
    DOCKERFILE_PATH: 2.0-php8.0/Dockerfile
    VERSION_TYPE: docker_env
  image: mwalbeck/determine-docker-tags
  name: determine tags
  pull: if-not-exists
- image: plugins/docker
  name: build and publish
  pull: if-not-exists
  settings:
    dockerfile: 2.0-php8.0/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/composer
    username:
      from_secret: dockerhub_username
- image: plugins/matrix
  name: notify
  pull: if-not-exists
  settings:
    homeserver: https://matrix.mwalbeck.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
  when:
    status:
    - failure
    - success
trigger:
  branch:
  - master
  event:
  - push
type: docker
---
kind: signature
hmac: 625dab74ac2f987a92f9905ff81b89c807d2d8347ba268bdcacbb65547af652b

...
